# Generated by Django 2.2.16 on 2020-09-30 13:49

from django.db import migrations


# This is required for permissions and co
def migrate_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="django_zencoder").update(
        app_label="django_video_encoder"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("django_zencoder", "0004_auto_20170729_1732"),
    ]

    operations = [
        migrations.RunPython(
            migrate_content_types, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterModelTable(
            name="format",
            table="django_video_encoder_format",
        ),
        migrations.AlterModelTable(
            name="thumbnail",
            table="django_video_encoder_thumbnail",
        ),
        # Black doesn't like SQL statements `\"`
        # fmt: off
        # Pre-faking the initial migrations as the upcoming version breaks also migration
        # history
        migrations.RunSQL(
            "INSERT INTO django_migrations (\"app\", \"name\", \"applied\") "
            "VALUES ('django_video_encoder', '0001_initial', NOW());"
        ),
        # fmt: on
    ]
