# Generated by Django 2.2.16 on 2020-09-30 13:49

from django.db import migrations


# TODO: apparently required for permissions and co
def migrate_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="django_zencoder").update(
        app_label="django_video_encoder"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("django_video_encoder", "0004_auto_20170729_1732"),
    ]

    operations = [
        migrations.RunPython(
            migrate_content_types, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterModelTable(
            name="format",
            table="django_video_encoder_format",
        ),
        migrations.AlterModelTable(
            name="thumbnail",
            table="django_video_encoder_thumbnail",
        ),
        # We will start migrations from scratch after renaming in the next release
        # This will cause the migrations to always seem "unapplied".
        # Delete all but initial migration
        migrations.RunSQL(
            "DELETE FROM django_migrations "
            "WHERE app = 'django_video_encoder' "
            "AND name != '0001_initial';"
        ),
    ]
